
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/carts
  application:
    name: CartService
#  data: 
#    mongodb: 
#      database: demo
#      uri: mongodb+srv://dbmongo:jsjS%40480@e-commerce-db.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
#
#  config:
#    import: optional:configserver:http://localhost:8081


eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/

      


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


server:
  port: 9080