spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
  application:
    name: product-service


server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG