
spring:
  application:
    name: OrderService
  data:
    mongodb:
      uri: mongodb://localhost:27017/orders
server:
  port: 8822
  
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
